### PR TITLE
Support for user other then root and couple of other fixes

### PR DESCRIPTION
**Pull request by cardil**
Hi,

I've added support to run forge server with user other then `root` for security reasons. I've also added some changes that by default it uses `puma` rack server, and to be able to specify what version of forge gem to use.

### CODE REVIEW

**Comment by cardil** [comment]
For now, I've published this version here: https://hub.docker.com/r/coigovpl/puppet-forge-server/. If you accept this pull request, I think I will delete this repo, to avoid segmentation on docker hub.

**Comment by m4ce** [comment]
Thanks for the pull request.

I have some doubt over the puma changes. Puppet Forge Server uses sinatra on top of rack. I am not sure how your change can make it work with Puma by just instaling the gem?

As for the security changes related to running the forge under a non-privileged user, I'm happy with that. Only catch is that if one wants to pass a data volume rw to the container (for cache, modules etc.), you may need to create the user also on the host, which limits partability.

Cheers,
Matteo

**Comment by cardil** [comment]
Ad. puma: Puma server will be used automatically instead of webrick. See here:

[asciicast](https://asciinema.org/a/32089)

Ad. running as different user. You can run data only containers to operate on data if you like (https://medium.com/@ramangupta/why-docker-data-containers-are-good-589b3c6c749e#.x9lvftxua), or create user with same uid.

**Comment by m4ce** [comment]
Alright then, thanks for the work!

**Pull request merged**
